- hosts: worker
  tasks:
    - name: Install server
      become: yes
      apt: name={{ item }} state=latest update_cache=true
      with_items:
        - nginx
        - php
        - composer
        - git
    - name: Clone repository
      git:
        repo: 'https://github.com/udinIMM/Hackathon.git'
        dest: ~/Hackathon
    - name: Copy .env
      copy: src=./.env dest=~/Hackathon/.env
    - name: Set ngin root
      copy: src=./default dest=/etc/nginx/sites-available/default