version: '3.3'

services:
    db:
        image: mysql:5.7
        volumes:
            - dbdata_fp:/var/lib/mysql
            - ./schema2.sql:/docker-entrypoint-initdb.d/1.sql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 123
            MYSQL_DATABASE: zoya
            MYSQL_USER: ikiuser
            MYSQL_PASSWORD: 123
            MYSQL_ROOT_HOST: '%'
    worker1:
        depends_on:
            - db
        build:
            context: worker1/
        environment:
            DB_HOST: db
            DB_NAME: zoya
            DB_USERNAME: ikiuser
            DB_PASSWORD: 123
    worker2:
        depends_on:
            - db
        build:
            context: worker1/
        environment:
            DB_HOST: db
            DB_NAME: zoya
            DB_USERNAME: ikiuser
            DB_PASSWORD: 123
    worker3:
        depends_on:
            - db
        build:
            context: worker1/
        environment:
            DB_HOST: db
            DB_NAME: zoya
            DB_USERNAME: ikiuser
            DB_PASSWORD: 123
    balancer:
        image: nginx
        ports:
            - "9005:80"
        volumes:
            - ./default1.conf:/etc/nginx/conf.d/default.conf
        links:
            - worker1:worker1
            - worker2:worker2
            - worker3:worker3
volumes:
    dbdata_fp:

