version: '3.3'

services:
    db:
        image: mysql:5.7
        volumes:
            - dbdata:/var/lib/mysql
            - ./reservasi.sql:/docker-entrypoint-initdb.d/init.sql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: buayakecil
            MYSQL_DATABASE: reservasi
            MYSQL_USER: userawan
            MYSQL_PASSWORD: buayakecil
    worker1:
        depends_on:
            - db
        build:
            context: worker1/
        environment:
            DB_HOST: db
            DB_NAME: reservasi
            DB_USERNAME: userawan
            DB_PASSWORD: buayakecil
    worker2:
        depends_on:
            - db
        build:
            context: worker2/
        environment:
            DB_HOST: db
            DB_NAME: reservasi
            DB_USERNAME: userawan
            DB_PASSWORD: buayakecil
    worker3:
        depends_on:
            - db
        build:
            context: worker3/
        environment:
            DB_HOST: db
            DB_NAME: reservasi
            DB_USERNAME: userawan
            DB_PASSWORD: buayakecil
    balancer:
        image: nginx
        ports:
            - "9000:80"
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf
        links:
            - worker1:worker1
            - worker2:worker2
            - worker3:worker3
volumes:
    dbdata:

